name: Sync Image to ACR
run-name: Sync ghcr/dockerhub image to aliyun acr
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Aliyun ACR
        env:
          ACR_REGISTRY: ${{ secrets.ACR_REGISTRY }}
          ACR_USER: ${{ secrets.ACR_USER }}
          ACR_PWD: ${{ secrets.ACR_PWD }}
        run: |
          echo ${{ secrets.ACR_PWD }} | docker login ${{ secrets.ACR_REGISTRY }} -u ${{ secrets.ACR_USER }} --password-stdin

      # 同步 php:7.4-apache
      - name: Pull & Push php:7.4-apache
        run: |
          docker pull docker.io/library/php:7.4-apache
          docker tag docker.io/library/php:7.4-apache ${{ secrets.ACR_REGISTRY }}/majun-namespace/php:7.4-apache
          docker push ${{ secrets.ACR_REGISTRY }}/majun-namespace/php:7.4-apache

      # 同步 mysql:5.7
      - name: Pull & Push mysql:5.7
        run: |
          docker pull docker.io/library/mysql:5.7
          docker tag docker.io/library/mysql:5.7 ${{ secrets.ACR_REGISTRY }}/majun-namespace/mysql:5.7
          docker push ${{ secrets.ACR_REGISTRY }}/majun-namespace/mysql:5.7
