name: Sync Image to ACR
run-name: Sync ghcr/dockerhub image to aliyun acr
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Aliyun ACR
        env:
          ACR_REGISTRY: ${{ secrets.ACR_REGISTRY }}
          ACR_USER: ${{ secrets.ACR_USER }}
          ACR_PWD: ${{ secrets.ACR_PWD }}
        run: |
          echo ${{ secrets.ACR_PWD }} | docker login ${{ secrets.ACR_REGISTRY }} -u ${{ secrets.ACR_USER }} --password-stdin

      # 同步 home-assistant
      - name: Pull & Push home-assistant
        run: |
          docker pull ghcr.io/home-assistant/home-assistant:latest
          docker tag ghcr.io/home-assistant/home-assistant:latest ${{ secrets.ACR_REGISTRY }}/majun-namespace/majun-repo:latest
          docker push ${{ secrets.ACR_REGISTRY }}/majun-namespace/majun-repo:latest

      # 同步 nginx
      - name: Pull & Push nginx
        run: |
          docker pull docker.io/library/nginx:latest
          docker tag docker.io/library/nginx:latest ${{ secrets.ACR_REGISTRY }}/majun-namespace/nginx:latest
          docker push ${{ secrets.ACR_REGISTRY }}/majun-namespace/nginx:latest
